import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/PageStyles/Home.module.css'
import NavBar from '../components/NavBar'
import { useUser } from '@auth0/nextjs-auth0/client'


const inter = Inter({ subsets: ['latin'] })



export default function Home() {
  const { user } = useUser()
  
  return (
    <>
      <Head>
        <title>Portfolio Generator</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <header>
          <NavBar user={user} />
          
        </header>
        <section>

        </section>
      </main>
    </>
  )
}
